# Generated by Django 3.1.2 on 2021-02-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentCache',
            fields=[
                ('cache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autoreduce_webapp.cache')),
                ('id_name', models.IntegerField()),
                ('start_date', models.TextField(default='')),
                ('end_date', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('instrument', models.TextField(default='')),
                ('pi', models.TextField(default='')),
            ],
            bases=('autoreduce_webapp.cache',),
        ),
        migrations.CreateModel(
            name='InstrumentCache',
            fields=[
                ('cache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autoreduce_webapp.cache')),
                ('id_name', models.CharField(max_length=80)),
                ('upcoming_experiments', models.TextField(blank=True)),
                ('valid_experiments', models.TextField(blank=True)),
            ],
            bases=('autoreduce_webapp.cache',),
        ),
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('cache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autoreduce_webapp.cache')),
                ('id_name', models.IntegerField()),
                ('associated_experiments', models.TextField(blank=True)),
                ('owned_instruments', models.TextField(blank=True)),
                ('valid_instruments', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_instrument_scientist', models.BooleanField(default=False)),
            ],
            bases=('autoreduce_webapp.cache',),
        ),
    ]
